import { PERMISSIONS, type PermissionCode } from '../common/constants';

const createPermissionGroup = <T extends readonly PermissionCode[]>(
  ...permissions: T
) => permissions;

export const EMPLOYEE_READ_PERMISSIONS = createPermissionGroup(
  PERMISSIONS.EMPLOYEES_READ,
  PERMISSIONS.EMPLOYEES_READ_UNIT,
  PERMISSIONS.EMPLOYEES_READ_OWN,
);

export const SALARY_READ_PERMISSIONS = createPermissionGroup(
  PERMISSIONS.SALARY_READ,
  PERMISSIONS.SALARY_READ_OWN,
);

export const LEAVE_READ_PERMISSIONS = createPermissionGroup(
  PERMISSIONS.LEAVES_READ,
  PERMISSIONS.LEAVES_READ_UNIT,
  PERMISSIONS.LEAVES_READ_OWN,
);

export const LEAVE_TYPE_ACCESS_PERMISSIONS = createPermissionGroup(
  ...LEAVE_READ_PERMISSIONS,
  PERMISSIONS.LEAVES_WRITE,
  PERMISSIONS.LEAVES_APPROVE,
);

export const LEAVE_QUEUE_ACCESS_PERMISSIONS = createPermissionGroup(
  ...LEAVE_READ_PERMISSIONS,
  PERMISSIONS.LEAVES_APPROVE,
);

export const LEAVE_CREATE_REQUEST_PERMISSIONS = createPermissionGroup(
  PERMISSIONS.LEAVES_WRITE,
  PERMISSIONS.LEAVES_APPROVE,
);

export const EDUCATION_READ_ACCESS_PERMISSIONS = createPermissionGroup(
  ...EMPLOYEE_READ_PERMISSIONS,
  PERMISSIONS.EDUCATION_READ,
  PERMISSIONS.EDUCATION_WRITE,
  PERMISSIONS.EDUCATION_APPROVE,
);

export const EDUCATION_WRITE_ACCESS_PERMISSIONS = createPermissionGroup(
  PERMISSIONS.EDUCATION_WRITE,
  PERMISSIONS.EMPLOYEES_WRITE,
  PERMISSIONS.EDUCATION_APPROVE,
);
